//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obj_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHMENTS_GROUPS
    {
        public decimal CODE { get; set; }
        public decimal BOTYPE { get; set; }
        public string NAME { get; set; }
        public string SHORTNAME { get; set; }
        public string DEF_EXT { get; set; }
        public decimal RIGHTS_SCHEME { get; set; }
        public string NOTE { get; set; }
    }
}
