//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obj_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESS_OBJECTS
    {
        public BUSINESS_OBJECTS()
        {
            this.BUSINESS_OBJECTS1 = new HashSet<BUSINESS_OBJECTS>();
        }
    
        public decimal CODE { get; set; }
        public decimal TYPE { get; set; }
        public decimal DOCCODE { get; set; }
        public string NAME { get; set; }
        public decimal OWNER { get; set; }
        public Nullable<decimal> CHECKOUT { get; set; }
        public decimal REVISION { get; set; }
        public string REVSIGN { get; set; }
        public decimal PRODCODE { get; set; }
        public Nullable<decimal> ACCESS_LEVEL { get; set; }
        public Nullable<decimal> TODAY_STATE { get; set; }
        public Nullable<System.DateTime> TODAY_STATEDATE { get; set; }
        public Nullable<decimal> TODAY_PRODBOCODE { get; set; }
        public Nullable<decimal> TODAY_PRODDOCCODE { get; set; }
        public Nullable<decimal> TODAY_STATEUSER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<decimal> CREATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> UPDATE_USER { get; set; }
        public Nullable<decimal> ATTACHMENTS_COUNT { get; set; }
    
        public virtual ICollection<BUSINESS_OBJECTS> BUSINESS_OBJECTS1 { get; set; }
        public virtual BUSINESS_OBJECTS BUSINESS_OBJECTS2 { get; set; }
        public virtual BUSINESSOBJ_STATES BUSINESSOBJ_STATES { get; set; }
    }
}
