//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obj_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESSOBJ_STATES
    {
        public BUSINESSOBJ_STATES()
        {
            this.BUSINESS_OBJECTS = new HashSet<BUSINESS_OBJECTS>();
            this.BUSINESSOBJ_STATES1 = new HashSet<BUSINESSOBJ_STATES>();
            this.BUSINESSOBJ_STATES11 = new HashSet<BUSINESSOBJ_STATES>();
            this.BUSINESSOBJ_STATES12 = new HashSet<BUSINESSOBJ_STATES>();
        }
    
        public decimal CODE { get; set; }
        public decimal BOTYPE { get; set; }
        public string NAME { get; set; }
        public string SHORTNAME { get; set; }
        public Nullable<decimal> RIGHTS_SCHEME { get; set; }
        public decimal MINSTATE { get; set; }
        public Nullable<decimal> ADDITIONAL_TO { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PROMLEVEL { get; set; }
        public System.DateTime RDATE { get; set; }
        public string NOTE { get; set; }
        public decimal REVCOUNT { get; set; }
        public decimal REVCOUNT_OTHER { get; set; }
        public decimal CATEGORY { get; set; }
        public Nullable<decimal> EXCEPT_ACTION { get; set; }
        public Nullable<decimal> TO_STATE { get; set; }
        public Nullable<decimal> OBJECTS_DEF { get; set; }
        public decimal DO_INHERIT { get; set; }
        public Nullable<decimal> SUBLEVEL { get; set; }
        public Nullable<decimal> MARKING_COLOR { get; set; }
        public Nullable<decimal> TO_STATE_BY_MAIL_CIRC { get; set; }
    
        public virtual ICollection<BUSINESS_OBJECTS> BUSINESS_OBJECTS { get; set; }
        public virtual ICollection<BUSINESSOBJ_STATES> BUSINESSOBJ_STATES1 { get; set; }
        public virtual BUSINESSOBJ_STATES BUSINESSOBJ_STATES2 { get; set; }
        public virtual ICollection<BUSINESSOBJ_STATES> BUSINESSOBJ_STATES11 { get; set; }
        public virtual BUSINESSOBJ_STATES BUSINESSOBJ_STATES3 { get; set; }
        public virtual ICollection<BUSINESSOBJ_STATES> BUSINESSOBJ_STATES12 { get; set; }
        public virtual BUSINESSOBJ_STATES BUSINESSOBJ_STATES4 { get; set; }
    }
}
