//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obj_lib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OmpModel : DbContext
    {
        public OmpModel()
            : base("name=OmpModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SEPO_TFLEX_OBJ_SYNCH> SEPO_TFLEX_OBJ_SYNCH { get; set; }
        public DbSet<SEPO_TFLEX_SIGN_DOCS> SEPO_TFLEX_SIGN_DOCS { get; set; }
        public DbSet<SEPO_TFLEX_SPEC_SECTIONS> SEPO_TFLEX_SPEC_SECTIONS { get; set; }
        public DbSet<V_SEPO_TFLEX_BO_TYPES> V_SEPO_TFLEX_BO_TYPES { get; set; }
        public DbSet<V_SEPO_TFLEX_OBJ_SYNCH> V_SEPO_TFLEX_OBJ_SYNCH { get; set; }
        public DbSet<BUSINESS_OBJECTS> BUSINESS_OBJECTS { get; set; }
        public DbSet<SPC_SECTIONS> SPC_SECTIONS { get; set; }
        public DbSet<BUSINESSOBJ_STATES> BUSINESSOBJ_STATES { get; set; }
        public DbSet<ATTACHMENTS_GROUPS> ATTACHMENTS_GROUPS { get; set; }
    }
}
