//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obj_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEPO_TFLEX_OBJ_SYNCH
    {
        public decimal ID { get; set; }
        public decimal TFLEX_SECTION { get; set; }
        public Nullable<decimal> TFLEX_DOCSIGN { get; set; }
        public decimal OMP_BOTYPE { get; set; }
        public decimal OMP_BOSTATE { get; set; }
        public Nullable<decimal> OMP_FILEGROUP { get; set; }
        public Nullable<decimal> OMP_OWNER { get; set; }
        public decimal OMP_SECTION { get; set; }
    
        public virtual SEPO_TFLEX_SPEC_SECTIONS SEPO_TFLEX_SPEC_SECTIONS { get; set; }
        public virtual SEPO_TFLEX_SIGN_DOCS SEPO_TFLEX_SIGN_DOCS { get; set; }
    }
}
