//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obj_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEPO_TFLEX_SPEC_SECTIONS
    {
        public SEPO_TFLEX_SPEC_SECTIONS()
        {
            this.SEPO_TFLEX_OBJ_SYNCH = new HashSet<SEPO_TFLEX_OBJ_SYNCH>();
        }
    
        public decimal ID { get; set; }
        public string SECTION_ { get; set; }
    
        public virtual ICollection<SEPO_TFLEX_OBJ_SYNCH> SEPO_TFLEX_OBJ_SYNCH { get; set; }
    }
}
