//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obj_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPC_SECTIONS
    {
        public decimal CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> DEFTYPE { get; set; }
        public Nullable<decimal> NUM { get; set; }
        public decimal ORDERNUM { get; set; }
        public decimal UNDERLINE { get; set; }
        public decimal ROWS_BEFORE { get; set; }
        public decimal ROWS_AFTER { get; set; }
    }
}
