//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obj_lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SEPO_TFLEX_BO_TYPES
    {
        public decimal BOTYPE { get; set; }
        public string BOTYPENAME { get; set; }
        public string BOTYPESHORTNAME { get; set; }
    }
}
